### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod#6]
HOPE is getting a lot of internal server errors from hommod. In the logs I see:

```
[2016-03-02 08:26:38 +0000] [2167] [ERROR] Error handling request
Traceback (most recent call last):
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 159, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/www/hommod/hommod-rest/hommod_rest/middleware.py", line 44, in __call__
    return self.app(environ, start_response)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 841, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/srv/www/hommod/.virtualenvs/hommod-rest/local/lib/python2.7/site-packages/werkzeug/test.py", line 867, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
```

**Comment by jonblack** [comment]
This bug is the root cause of the internal server errors being received by HOPE. I've traced it down to the following endpoint in hommod-rest:

```
@bp.route('/get_metadata/<jobid>/', methods=['GET'])
def get_metadata(jobid):

    """
    Get the metadata of the model, created by the modeling job.

    :param jobid: the jobid returned by 'submit'
    :return: The json metadata object. If the job status is not SUCCESS,
             this method returns an error.
    """

    _log.info("metadata request for job %s" % jobid)

    from hommod_rest.application import celery
    result = celery.AsyncResult(jobid)
    path = result.result
    if not path:
        return {}

    try:
        data = extract_info(path)
        data['alignment'] = extract_alignment(path)
    except:
        _log.warn('failed to get all data from %s' % path)
        return ''

    _log.info("metadata successfully retrieved for job %s" % jobid)

    return jsonify(data)
```

By returning an empty string after the first log statement, the crash is avoided. This workaround is currently in production.

We can look at this when the new server is up and running because by then we should have hommod in a docker container which will make debugging much easier.

**Comment by cbaakman** [comment]
Isn't the 'return {}' the problem?

**Comment by cbaakman** [comment]
Hommod is now running in a docker container and get_metadata was entirely rewritten in https://github.com/cmbi/hommod/commit/efb05f51a29fe56786f2c148ff490bc35b96dc51, so I'm closing this issue.
